version: '3.8'
services:
   mysqldb:
      image: mysql:8.0
      restart: always
      environment:
          - MYSQL_DATABASE=test
          - MYSQL_ROOT_PASSWORD=11111
      ports:
          - "8989:3306"
      volumes:
          - "./data/db/mysql:/var/lib/mysql"
          - "./db/init.sql/create_dev_user.sql:/docker-entrypoint-initdb.d/1.sql"
volumes:
  mysql:
    driver: local